version: '3.8'

services:
  dev:
    container_name: proxyma-api-dev
    image: proxyma-api-dev:${VERSION}
    build:
      context: .
      target: development
    command: npm run start:debug
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - proxyma-api-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  prod:
    container_name: proxyma-api-prod
    image: proxyma-api-prod:${VERSION}
    build:
      context: .
      target: production
    command: npm run start:prod
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - proxyma-api-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  postgres:
    container_name: postgres
    image: postgres:14
    networks:
      - proxyma-api-network
    environment:
      PG_DATA: /var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  proxyma-api-network:

volumes:
  pgdata: